# Generated by Django 4.0.4 on 2022-05-21 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ajaxapp', '0003_remove_student_email_remove_student_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Phone',
            new_name='phone',
        ),
    ]
