# Generated by Django 4.0.4 on 2022-05-21 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ajaxapp', '0004_rename_phone_student_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
